name: Prepare Release Cascade

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Target semantic version (ex: 0.1.16)"
        required: true

jobs:
  update-manifest:
    name: Update VERSION in lcod-release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.LCOD_RELEASE_TOKEN }}
    outputs:
      branch: ${{ steps.meta.outputs.branch }}
    steps:
      - name: Checkout lcod-release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git credentials
        run: gh auth setup-git

      - name: Configure authenticated remote
        run: git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

      - name: Configure git author
        run: |
          git config user.name "lcod-release-bot"
          git config user.email "releases@lcod.team"

      - name: Update VERSION file
        run: |
          echo "${{ inputs.version }}" > VERSION

      - name: Commit and push branch
        id: meta
        env:
          VERSION: ${{ inputs.version }}
        run: |
          branch="release/v${VERSION}"
          if git diff --quiet --exit-code; then
            echo "VERSION file already set to ${VERSION}, skipping commit."
            echo "branch=${branch}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          git checkout -b "$branch"
          git add VERSION
          git commit -m "chore(release): set version to ${VERSION}"
          git push origin "$branch"
          echo "branch=${branch}" >> "$GITHUB_OUTPUT"

      - name: Open pull request
        if: steps.meta.outputs.branch != ''
        env:
          GH_TOKEN: ${{ secrets.LCOD_RELEASE_TOKEN }}
          VERSION: ${{ inputs.version }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          BRANCH: ${{ steps.meta.outputs.branch }}
        run: |
          existing="$(gh pr list --head "${BRANCH}" --json number --jq '.[0].htmlUrl' || true)"
          if [[ -n "${existing}" ]]; then
            echo "- lcod-release: PR déjà ouvert (${existing})" >> "$GITHUB_STEP_SUMMARY"
            exit 0
          fi

          pr_url="$(gh pr create \
            --base main \
            --head "${BRANCH}" \
            --title "chore(release): set version to ${VERSION}" \
            --body "Automated version bump to ${VERSION} triggered from ${RUN_URL}." \
            --label release)"

          echo "- lcod-release: ${pr_url}" >> "$GITHUB_STEP_SUMMARY"

  propagate-version:
    name: Prepare bumps in downstream repositories
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.LCOD_RELEASE_TOKEN }}
    needs: update-manifest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson('["lcod-team/lcod-kernel-rs","lcod-team/lcod-kernel-js","lcod-team/lcod-kernel-java","lcod-team/lcod-cli"]') }}
    steps:
      - name: Checkout orchestrator
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git credentials
        run: gh auth setup-git

      - name: Configure authenticated remote
        run: git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: target
          fetch-depth: 0
          token: ${{ secrets.LCOD_RELEASE_TOKEN }}

      - name: Setup git credentials (target repo)
        working-directory: target
        run: gh auth setup-git

      - name: Configure authenticated remote (target repo)
        working-directory: target
        run: git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ matrix.repo }}.git

      - name: Configure git author
        working-directory: target
        run: |
          git config user.name "lcod-release-bot"
          git config user.email "releases@lcod.team"

      - name: Sync version
        env:
          LCOD_VERSION: ${{ inputs.version }}
        run: |
          ./scripts/sync-version.sh target

      - name: Commit and open pull request
        env:
          VERSION: ${{ inputs.version }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GH_TOKEN: ${{ secrets.LCOD_RELEASE_TOKEN }}
        run: |
          cd target
          if git status --porcelain --untracked-files=no | grep -q '.'; then
            branch="release/v${VERSION}"
            git checkout -b "${branch}"
            git add -A
            git commit -m "chore(release): bump version to ${VERSION}"
            git push origin "${branch}" --force-with-lease

            existing="$(gh pr list --head "${branch}" --json number --jq '.[0].htmlUrl' || true)"
            if [[ -z "${existing}" ]]; then
              pr_url="$(gh pr create \
                --base main \
                --head "${branch}" \
                --title "chore(release): bump version to ${VERSION}" \
                --body "Automated bump to ${VERSION} triggered from ${RUN_URL} via lcod-release." \
                --label release)"
            else
              pr_url="${existing}"
            fi

            echo "- ${{ matrix.repo }}: ${pr_url}" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "- ${{ matrix.repo }}: aucune modification nécessaire" >> "$GITHUB_STEP_SUMMARY"
          fi
